title: Przykładowy tytuł

sinol_task_id: abc

memory_limit: 262144 # kB

time_limit: 1000 # milliseconds

scores:
  1: 40
  2: 60


# For more options see: https://github.com/sio2project/sinol-make/blob/main/example_package/config.yml
# Or here are some basic ones.


### Interactive tasks

# Extra compilation arguments can be defined in `extra_compile_args` key.
# Each language can have different extra arguments.
# Additional files used in compilation can be defined in `extra_compilation_files` key.
# They are copied to the directory where the source code is compiled.
# All languages have the same additional files.

# extra_compilation_args:
#   cpp: ['abclib.cpp']

# extra_compilation_files: ['abclib.cpp', 'abclib.h']


### Memory

# More precise memory limits can be defined in `memory_limits` key.
# Same as with time limits, the more precise memory limit has higher priority.

# memory_limits:
#   3: 131072
#   4: 131072


### Time

# More precise time limit for each group or test can be defined in `time_limits` key.
# The more precise time limit has higher priority (first group, then global time limit).

# time_limits:
#   2: 2000
#   5: 7000


### Title

# Title can be different for different languages.
# If there are Polish characters, they should be written for better readability.
# title_pl: Przykładowe zadanie
# title_en: Example task package